package blue.sparse.minecraft.common.biome

object BiomeOcean: BiomeType("ocean")
object BiomePlains: BiomeType("plains", 0.8f, 0.4f)
object BiomeDesert: BiomeType("desert", 2.0f, 0.0f)
object BiomeHills: BiomeType("extreme_hills", 0.2f, 0.3f)
object BiomeForest: BiomeType("forest", 0.7f, 0.8f)
object BiomeTaiga: BiomeType("taiga", 0.25f, 0.8f)
object BiomeSwamp: BiomeType("swampland", 0.8f, 0.9f)
object BiomeRiver: BiomeType("river")
object BiomeHell: BiomeType("hell", 2.0f, 0.0f)
object BiomeEnd: BiomeType("sky")
object BiomeFrozenOcean: BiomeType("frozen_ocean", 0.0f, 0.5f)
object BiomeFrozenRiver: BiomeType("frozen_river", 0.0f, 0.5f)
object BiomeIceFlats: BiomeType("ice_flats", 0.0f, 0.5f)
object BiomeIceMountains: BiomeType("ice_mountains", 0.0f, 0.5f)
object BiomeMushroomIsland: BiomeType("mushroom_island", 0.9f, 1.0f)
object BiomeMushroomIslandShore: BiomeType("mushroom_island_shore", 0.9f, 1.0f)
object BiomeBeach: BiomeType("beaches", 0.8f, 0.4f)
object BiomeDesertHills: BiomeType("desert_hills", 2.0f, 0.0f)
object BiomeForestHills: BiomeType("forest_hills", 0.7f, 0.8f)
object BiomeTaigaHills: BiomeType("taiga_hills", 0.25f, 0.8f)
object BiomeSmallHills: BiomeType("smaller_extreme_hills", 0.2f, 0.3f)
object BiomeJungle: BiomeType("jungle", 0.95f, 0.9f)
object BiomeJungleHills: BiomeType("jungle_hills", 0.95f, 0.9f)
object BiomeJungleEdge: BiomeType("jungle_edge", 0.95f, 0.8f)
object BiomeDeepOcean: BiomeType("deep_ocean")
object BiomeStoneBeach: BiomeType("stone_beach", 0.2f, 0.3f)
object BiomeColdBeach: BiomeType("cold_beach", 0.05f, 0.3f)
object BiomeForestBirch: BiomeType("birch_forest", 0.6f, 0.6f)
object BiomeForestBirchHills: BiomeType("birch_forest_hills", 0.6f, 0.6f)
object BiomeForestRoofed: BiomeType("roofed_forest", 0.7f, 0.8f)
object BiomeTaigaCold: BiomeType("taiga_cold", rainfall = 0.4f)
object BiomeTaigaColdHills: BiomeType("taiga_cold_hills", rainfall = 0.4f)
object BiomeTaigaMega: BiomeType("redwood_taiga", 0.3f, 0.8f)
object BiomeTaigaMegaHills: BiomeType("redwood_taiga_hills", 0.3f, 0.8f)
object BiomeHillsTrees: BiomeType("extreme_hills_with_trees", 0.2f, 0.3f)
object BiomeSavanna: BiomeType("savanna", 1.2f, 0.0f)
object BiomeSavannaRock: BiomeType("savanna_rock", 1.0f, 0.0f)
object BiomeMesa: BiomeType("mesa", 2.0f, 0.0f)
object BiomeMesaRock: BiomeType("mesa_rock", 2.0f, 0.0f)
object BiomeMesaClearRock: BiomeType("mesa_clear_rock", 2.0f, 0.0f)
object BiomeVoid: BiomeType("void")
object BiomePlainsMutated: BiomeType("mutated_plains", 0.8f, 0.4f)
object BiomeDesertMutated: BiomeType("mutated_desert", 2.0f, 0.0f)
object BiomeHillsMutated: BiomeType("mutated_extreme_hills", 0.2f, 0.3f)
object BiomeForestMutated: BiomeType("mutated_forest", 0.7f, 0.8f)
object BiomeTaigaMutated: BiomeType("mutated_taiga", 0.25f, 0.8f)
object BiomeSwampMutated: BiomeType("mutated_swampland", 0.8f, 0.9f)
object BiomeIceFlatsMutated: BiomeType("mutated_ice_flats", 0.0f, 0.5f)
object BiomeJungleMutated: BiomeType("mutated_jungle", 0.95f, 0.9f)
object BiomeJungleEdgeMutated: BiomeType("mutated_jungle_edge", 0.95f, 0.8f)
object BiomeForestBirchMutated: BiomeType("mutated_birch_forest", 0.6f, 0.6f)
object BiomeForestBirchHillsMutated: BiomeType("mutated_birch_forest_hills", 0.6f, 0.6f)
object BiomeForestRoofedMutated: BiomeType("mutated_roofed_forest", 0.7f, 0.8f)
object BiomeTaigaColdMutated: BiomeType("mutated_taiga_cold", rainfall = 0.4f)
object BiomeTaigaMegaMutated: BiomeType("mutated_redwood_taiga", 0.25f, 0.8f)
object BiomeTaigaMegaHillsMutated: BiomeType("mutated_redwood_taiga_hills", 0.25f, 0.8f)
object BiomeHillsTreesMutated: BiomeType("mutated_extreme_hills_with_trees", 0.2f, 0.3f)
object BiomeSavannaMutated: BiomeType("mutated_savanna", 1.1f, 0.0f)
object BiomeSavannaRockMutated: BiomeType("mutated_savanna_rock", 1.0f, 0.0f)
object BiomeMesaMutated: BiomeType("mutated_mesa", 2.0f, 0.0f)
object BiomeMesaRockMutated: BiomeType("mutated_mesa_rock", 2.0f, 0.0f)
object BiomeMesaClearRockMutated: BiomeType("mutated_mesa_clear_rock", 2.0f, 0.0f)