package blue.sparse.minecraft.common.item.impl

import blue.sparse.minecraft.common.item.ItemType
import blue.sparse.minecraft.common.item.impl.types.*
import blue.sparse.minecraft.common.item.impl.types.armor.*
import blue.sparse.minecraft.common.item.impl.types.tools.ItemTypeTool
import blue.sparse.minecraft.common.item.impl.types.tools.ItemTypeWeapon

/**
 * EDIBLE ITEM TYPES
 */
object ItemTypeApple:               ItemTypeEdible("apple")
object ItemTypeAppleGolden:         ItemTypeEdible("apple_golden")
object ItemTypeBeefCooked:          ItemTypeEdible("beef_cooked")
object ItemTypeBeefRaw:             ItemTypeEdible("beef_raw")
object ItemTypeBeetrootSoup:        ItemTypeEdible("beetroot_soup", 1)
object ItemTypeBread:               ItemTypeEdible("bread")
object ItemTypeCake:                ItemTypeEdible("cake", 1)
object ItemTypeCarrot:              ItemTypeEdible("carrot")
object ItemTypeCarrotGolden:        ItemTypeEdible("carrot_golden")
object ItemTypeChickenCooked:       ItemTypeEdible("chicken_cooked")
object ItemTypeChickenRaw:          ItemTypeEdible("chicken_raw")
object ItemTypeChorusFruit:         ItemTypeEdible("chorus_fruit")
object ItemTypeCookie:              ItemTypeEdible("cookie")
object ItemTypeFishClownfishRaw:    ItemTypeEdible("fish_clownfish_raw")
object ItemTypeFishCodCooked:       ItemTypeEdible("fish_cod_cooked")
object ItemTypeFishCodRaw:          ItemTypeEdible("fish_cod_raw")
object ItemTypeFishPufferfishRaw:   ItemTypeEdible("fish_pufferfish_raw")
object ItemTypeFishSalmonCooked:    ItemTypeEdible("fish_salmon_cooked")
object ItemTypeFishSalmonRaw:       ItemTypeEdible("fish_salmon_raw")
object ItemTypeMelon:               ItemTypeEdible("melon")
object ItemTypeBucketMilk:          ItemTypeEdible("bucket_milk", 1)
object ItemTypeMushroomStew:        ItemTypeEdible("mushroom_stew", 1)
object ItemTypeMuttonCooked:        ItemTypeEdible("mutton_cooked")
object ItemTypeMuttonRaw:           ItemTypeEdible("mutton_raw")
object ItemTypePorkChopCooked:      ItemTypeEdible("porkchop_cooked")
object ItemTypePorkChopRaw:         ItemTypeEdible("porkchop_raw")
object ItemTypePotato:              ItemTypeEdible("potato")
object ItemTypePotatoBaked:         ItemTypeEdible("potato_baked")
object ItemTypePotatoPoisonous:     ItemTypeEdible("potato_poisonous")
object ItemTypePumpkinPie:          ItemTypeEdible("pumpkin_pie")
object ItemTypeRabbitCooked:        ItemTypeEdible("rabbit_cooked")
object ItemTypeRabbitRaw:           ItemTypeEdible("rabbit_raw")
object ItemTypeRabbitStew:          ItemTypeEdible("rabbit_stew")
object ItemTypeSpiderEye:           ItemTypeEdible("spider_eye")

/**
 * BOAT ITEM TYPES
 */
object ItemTypeAcaciaBoat:          ItemTypeBoat("acacia_boat")
object ItemTypeBirchBoat:           ItemTypeBoat("birch_boat")
object ItemTypeDarkOakBoat:         ItemTypeBoat("dark_oak_boat")
object ItemTypeJungleBoat:          ItemTypeBoat("jungle_boat")
object ItemTypeOakBoat:             ItemTypeBoat("oak_boat")
object ItemTypeSpruceBoat:          ItemTypeBoat("spruce_boat")

/**
 * ARMOR ITEM TYPES
 */
object ItemTypeChainmailHelmet:     ItemTypeHelmet("chainmail_helmet", 166)
object ItemTypeDiamondHelmet:       ItemTypeHelmet("diamond_helmet",  364)
object ItemTypeGoldHelmet:          ItemTypeHelmet("gold_helmet",  78)
object ItemTypeIronHelmet:          ItemTypeHelmet("iron_helmet",  166)

object ItemTypeChainmailChestplate: ItemTypeChestplate("chainmail_chestplate", 241)
object ItemTypeDiamondChestplate:   ItemTypeChestplate("diamond_chestplate", 529)
object ItemTypeGoldChestplate:      ItemTypeChestplate("gold_chestplate", 113)
object ItemTypeIronChestplate:      ItemTypeChestplate("iron_chestplate", 241)

object ItemTypeChainmailLeggings:   ItemTypeLeggings("chainmail_leggings", 226)
object ItemTypeDiamondLeggings:     ItemTypeLeggings("diamond_leggings", 496)
object ItemTypeGoldLeggings:        ItemTypeLeggings("gold_leggings", 106)
object ItemTypeIronLeggings:        ItemTypeLeggings("iron_leggings", 226)

object ItemTypeChainmailBoots:      ItemTypeBoots("chainmail_boots", 196)
object ItemTypeDiamondBoots:        ItemTypeBoots("diamond_boots", 430)
object ItemTypeGoldBoots:           ItemTypeBoots("gold_boots", 92 )
object ItemTypeIronBoots:           ItemTypeBoots("iron_boots", 196)

/**
 * TOOL ITEM TYPES
 */
object ItemTypeDiamondSword:        ItemTypeWeapon("diamond_sword", 1562)
object ItemTypeGoldSword:           ItemTypeWeapon("gold_sword", 33)
object ItemTypeIronSword:           ItemTypeWeapon("iron_sword", 251)
object ItemTypeStoneSword:          ItemTypeWeapon("stone_sword", 132)
object ItemTypeWoodSword:           ItemTypeWeapon("wood_sword", 60)

object ItemTypeDiamondPickaxe:      ItemTypeTool("diamond_pickaxe", 1562)
object ItemTypeGoldPickaxe:         ItemTypeTool("gold_pickaxe", 33)
object ItemTypeIronPickaxe:         ItemTypeTool("iron_pickaxe", 251)
object ItemTypeStonePickaxe:        ItemTypeTool("stone_pickaxe", 132)
object ItemTypeWoodPickaxe:         ItemTypeTool("wood_pickaxe", 60)

object ItemTypeDiamondAxe:          ItemTypeWeapon("diamond_axe", 1562)
object ItemTypeGoldAxe:             ItemTypeWeapon("gold_axe", 33)
object ItemTypeIronAxe:             ItemTypeWeapon("iron_axe", 251)
object ItemTypeStoneAxe:            ItemTypeWeapon("stone_axe", 132)
object ItemTypeWoodAxe:             ItemTypeWeapon("wood_axe", 60)

object ItemTypeDiamondShovel:       ItemTypeTool("diamond_shovel", 1562)
object ItemTypeGoldShovel:          ItemTypeTool("gold_shovel", 33)
object ItemTypeIronShovel:          ItemTypeTool("iron_shovel", 251)
object ItemTypeStoneShovel:         ItemTypeTool("stone_shovel", 132)
object ItemTypeWoodShovel:          ItemTypeTool("wood_shovel", 60)

object ItemTypeDiamondHoe:          ItemTypeTool("diamond_hoe", 1562)
object ItemTypeGoldHoe:             ItemTypeTool("gold_hoe", 33)
object ItemTypeIronHoe:             ItemTypeTool("iron_hoe", 251)
object ItemTypeStoneHoe:            ItemTypeTool("stone_hoe", 132)
object ItemTypeWoodHoe:             ItemTypeTool("wood_hoe", 60)

object ItemTypeShears:              ItemTypeDurable("shears", 238)

/**
 * DURABLE ITEM TYPES
 */
// TODO: Actually implement textures TOM | object ItemTypeFishingRod:          ItemTypeDurable("fishing_rod", 65)
object ItemTypeFlintAndSteel:       ItemTypeDurable("flint_and_steel", 65)
object ItemTypeCarrotOnAStick:      ItemTypeDurable("carrot_on_a_stick", 26)
object ItemTypeElytra:              ItemTypeDurable("elytra", 432)

/**
 * DOOR ITEM TYPES
 */
object ItemTypeDoorAcacia:          ItemTypeDoor("door_acacia")
object ItemTypeDoorBirch:           ItemTypeDoor("door_birch")
object ItemTypeDoorDarkOak:         ItemTypeDoor("door_dark_oak")
object ItemTypeDoorIron:            ItemTypeDoor("door_iron")
object ItemTypeDoorJungle:          ItemTypeDoor("door_jungle")
object ItemTypeDoorSpruce:          ItemTypeDoor("door_spruce")
object ItemTypeDoorWood:            ItemTypeDoor("door_wood")

/**
 * THROWABLE ITEM TYPES
 */
object ItemTypeSnowball:            ItemTypeThrowable("snowball")
object ItemTypeEnderPearl:          ItemTypeThrowable("ender_pearl")
object ItemTypeEgg:                 ItemTypeThrowable("egg")
object ItemTypeExperienceBottle:    ItemTypeThrowable("experience_bottle", 64)



object ItemTypeArrow: ItemType("arrow")
object ItemTypeBarrier: ItemType("barrier")
object ItemTypeBeetroot: ItemType("beetroot")
object ItemTypeBeetrootSeeds: ItemType("beetroot_seeds")
object ItemTypeBlazePowder: ItemType("blaze_powder")
object ItemTypeBlazeRod: ItemType("blaze_rod")
object ItemTypeBone: ItemType("bone")
object ItemTypeBookEnchanted: ItemType("book_enchanted")
object ItemTypeBookNormal: ItemType("book_normal")
object ItemTypeBookWritable: ItemType("book_writable")
object ItemTypeBookWritten: ItemType("book_written")
object ItemTypeBowl: ItemType("bowl")
object ItemTypeBrewingStand: ItemType("brewing_stand")
object ItemTypeBrick: ItemType("brick")
object ItemTypeBrokenElytra: ItemType("broken_elytra")
object ItemTypeBucketEmpty: ItemType("bucket_empty")
object ItemTypeBucketLava: ItemType("bucket_lava")
object ItemTypeBucketWater: ItemType("bucket_water")
object ItemTypeCauldron: ItemType("cauldron")
object ItemTypeCharcoal: ItemType("charcoal")
object ItemTypeChorusFruitPopped: ItemType("chorus_fruit_popped")
object ItemTypeClayBall: ItemType("clay_ball")
object ItemTypeCoal: ItemType("coal")
object ItemTypeComparator: ItemType("comparator")
object ItemTypeDiamond: ItemType("diamond")
object ItemTypeDiamondHorseArmor: ItemType("diamond_horse_armor")
object ItemTypeDragonBreath: ItemType("dragon_breath")
object ItemTypeDyePowderBlack: ItemType("dye_powder_black")
object ItemTypeDyePowderBlue: ItemType("dye_powder_blue")
object ItemTypeDyePowderBrown: ItemType("dye_powder_brown")
object ItemTypeDyePowderCyan: ItemType("dye_powder_cyan")
object ItemTypeDyePowderGray: ItemType("dye_powder_gray")
object ItemTypeDyePowderGreen: ItemType("dye_powder_green")
object ItemTypeDyePowderLightBlue: ItemType("dye_powder_light_blue")
object ItemTypeDyePowderLime: ItemType("dye_powder_lime")
object ItemTypeDyePowderMagenta: ItemType("dye_powder_magenta")
object ItemTypeDyePowderOrange: ItemType("dye_powder_orange")
object ItemTypeDyePowderPink: ItemType("dye_powder_pink")
object ItemTypeDyePowderPurple: ItemType("dye_powder_purple")
object ItemTypeDyePowderRed: ItemType("dye_powder_red")
object ItemTypeDyePowderSilver: ItemType("dye_powder_silver")
object ItemTypeDyePowderWhite: ItemType("dye_powder_white")
object ItemTypeDyePowderYellow: ItemType("dye_powder_yellow")
object ItemTypeEmerald: ItemType("emerald")
object ItemTypeEnderEye: ItemType("ender_eye")
object ItemTypeEndCrystal: ItemType("end_crystal")
object ItemTypeFeather: ItemType("feather")
object ItemTypeFireball: ItemType("fireball")
object ItemTypeFireworks: ItemType("fireworks")
object ItemTypeFlint: ItemType("flint")
object ItemTypeFlowerPot: ItemType("flower_pot")
object ItemTypeGhastTear: ItemType("ghast_tear")
object ItemTypeGlowstoneDust: ItemType("glowstone_dust")
object ItemTypeGoldHorseArmor: ItemType("gold_horse_armor")
object ItemTypeGoldIngot: ItemType("gold_ingot")
object ItemTypeGoldNugget: ItemType("gold_nugget")
object ItemTypeGunpowder: ItemType("gunpowder")
object ItemTypeHopper: ItemType("hopper")
object ItemTypeIronHorseArmor: ItemType("iron_horse_armor")
object ItemTypeIronIngot: ItemType("iron_ingot")
object ItemTypeIronNugget: ItemType("iron_nugget")
object ItemTypeItemFrame: ItemType("item_frame")
object ItemTypeKnowledgeBook: ItemType("knowledge_book")
object ItemTypeLead: ItemType("lead")
object ItemTypeLeather: ItemType("leather")
object ItemTypeMagmaCream: ItemType("magma_cream")
object ItemTypeMapEmpty: ItemType("map_empty")
//object ItemTypeMapFilled: ItemType("map_filled")
object ItemTypeMelonSpeckled: ItemType("melon_speckled")
object ItemTypeMinecartChest: ItemType("minecart_chest")
object ItemTypeMinecartCommandBlock: ItemType("minecart_command_block")
object ItemTypeMinecartFurnace: ItemType("minecart_furnace")
object ItemTypeMinecartHopper: ItemType("minecart_hopper")
object ItemTypeMinecartNormal: ItemType("minecart_normal")
object ItemTypeMinecartTnt: ItemType("minecart_tnt")
object ItemTypeNameTag: ItemType("name_tag")
object ItemTypeNetherBrick: ItemType("netherbrick")
object ItemTypeNetherStar: ItemType("nether_star")
object ItemTypeNetherWart: ItemType("nether_wart")
object ItemTypePainting: ItemType("painting")
object ItemTypePaper: ItemType("paper")
object ItemTypePrismarineCrystals: ItemType("prismarine_crystals")
object ItemTypePrismarineShard: ItemType("prismarine_shard")
object ItemTypeQuartz: ItemType("quartz")
object ItemTypeRabbitFoot: ItemType("rabbit_foot")
object ItemTypeRabbitHide: ItemType("rabbit_hide")
object ItemTypeRecordBlocks: ItemType("record_blocks")
object ItemTypeRecordCat: ItemType("record_cat")
object ItemTypeRecordChirp: ItemType("record_chirp")
object ItemTypeRecordFar: ItemType("record_far")
object ItemTypeRecordMall: ItemType("record_mall")
object ItemTypeRecordMellohi: ItemType("record_mellohi")
object ItemTypeRecordStal: ItemType("record_stal")
object ItemTypeRecordStrad: ItemType("record_strad")
object ItemTypeRecordWait: ItemType("record_wait")
object ItemTypeRecordWard: ItemType("record_ward")
object ItemTypeRedstoneDust: ItemType("redstone_dust")
object ItemTypeReeds: ItemType("reeds")
object ItemTypeRepeater: ItemType("repeater")
object ItemTypeRottenFlesh: ItemType("rotten_flesh")
object ItemTypeRuby: ItemType("ruby")
object ItemTypeSaddle: ItemType("saddle")
object ItemTypeSeedsMelon: ItemType("seeds_melon")
object ItemTypeSeedsPumpkin: ItemType("seeds_pumpkin")
object ItemTypeSeedsWheat: ItemType("seeds_wheat")
object ItemTypeShulkerShell: ItemType("shulker_shell")
object ItemTypeSign: ItemType("sign")
object ItemTypeSlimeBall: ItemType("slimeball")
object ItemTypeSpectralArrow: ItemType("spectral_arrow")
object ItemTypeSpiderEyeFermented: ItemType("spider_eye_fermented")
object ItemTypeStick: ItemType("stick")
object ItemTypeString: ItemType("string")
object ItemTypeStructureVoid: ItemType("structure_void")
object ItemTypeSugar: ItemType("sugar")
object ItemTypeTotem: ItemType("totem")
object ItemTypeWheat: ItemType("wheat")

